theme: jekyll-theme-midnight
title: Welcome to the Fall 2020 MECA 482: Ball on a Plate Project GitHub page!
descripition: We are Chico State engineering students working on a project in our Control System Design course. Here, you'll be able to see the process we went through to design and test our alogirithm. We've designed the physical system, dereived mathematical equations and models, and developed code in MATLAB/Simulink and Copelia Sim. Enjoy! 
